; Paquete de idioma español para MyPlot
; Traducido para PlotSquaredPM

; Popup al entrar a un terreno
popup=Has entrado al terreno {%0}
popup.owner=Propiedad de {%0}
popup.forsale=Este terreno está a la venta por {%0}. Usa /p buy para reclamar el terreno por ${%1}.
popup.available=Este terreno está libre. Usa /p rent para alquilar el terreno.
popup.denied=No tienes acceso a este terreno

; Comando /plot
command.name=plot
command.alias=p
command.desc=Reclama y administra tus terrenos
command.usage=/p [help]
command.unknown=Comando desconocido. Prueba /p help para ver la lista de comandos

subcommand.usage=Uso: {%0}

; Mensajes de formularios
form.header=Formulario MyPlot {%0}

; Errores mostrados cuando el jugador hace algo mal o el plugin falla.
error=§c¡Ups! Algo salió mal
notinplot=§cNo estás parado dentro de un terreno
notowner=§cNo eres el dueño de este terreno
plugin.disabled=§cEste plugin está deshabilitado
no.permissions=§cNo tienes los permisos necesarios!

confirm=confirm

; Subcomando /p help
help.name=help
help.desc=Muestra el menú de ayuda
help.usage=/p help [page: int]
help.header=--- Mostrando ayuda de MyPlot página {%0} de {%1} ---

; Subcomando /p addhelper
addhelper.name=addhelper
addhelper.alias=addh
addhelper.desc=Agrega un ayudante a tu terreno
addhelper.usage=/p addhelper <player: target>
addhelper.alreadyone={%0} ya es un ayudante de este terreno
addhelper.success={%0} ahora es un ayudante de este terreno
addhelper.form=Agregar Ayudante
addhelper.dropdown=Nombre del ayudante

; Subcomando /p removehelper
removehelper.name=removehelper
removehelper.alias=delh
removehelper.desc=Quita un ayudante de tu terreno
removehelper.usage=/p removehelper <player: target>
removehelper.notone={%0} no es un ayudante
removehelper.success={%0} ha sido removido de los ayudantes del terreno
removehelper.form=Quitar Ayudante
removehelper.dropdown=Nombre del ayudante
removehelper.formnohelpers=No hay ayudantes

; Subcomando /p denyplayer
denyplayer.name=denyplayer
denyplayer.alias=deny
denyplayer.desc=Niega el acceso a un jugador a tu terreno
denyplayer.usage=/p deny <player: target>
denyplayer.helper={%0} es un ayudante
denyplayer.alreadyone={%0} ya tiene acceso denegado a este terreno
denyplayer.notaplayer=Ese jugador no está en línea ahora mismo
denyplayer.cannotdeny={%0} no puede ser denegado
denyplayer.attempteddeny={%0} intentó negarte el acceso a su terreno
denyplayer.success1={%0} ahora tiene el acceso denegado al terreno
denyplayer.success2="Te han negado el acceso al terreno {%0};{%1} por {%2}"
denyplayer.form=Denegar Jugador
denyplayer.dropdown=Nombre del jugador

; Subcomando /p undenyplayer
undenyplayer.name=undenyplayer
undenyplayer.alias=undeny
undenyplayer.desc=Permite el acceso a un jugador a tu terreno
undenyplayer.usage=/p undeny <player: target>
undenyplayer.notone={%0} ya tiene acceso permitido
undenyplayer.success1={%0} ahora tiene acceso al terreno
undenyplayer.success2="Te han permitido el acceso al terreno {%0};{%1} por {%2}"
undenyplayer.form=Permitir Jugador
denyplayer.dropdown=Jugador Denegado
undenyplayer.formnodenied=No hay jugadores denegados

; Subcomando /p claim
claim.name=claim
claim.desc=Reclama el terreno actual donde estás
claim.usage=/p claim [name: string] [type: string]
claim.yourplot=Ya has reclamado este terreno
claim.alreadyclaimed=Este terreno ya está reclamado por {%0}
claim.maxplots=Has alcanzado el límite de {%0} terrenos por jugador
claim.nomoney=No tienes suficiente dinero para reclamar este terreno
claim.invalidtype=El tipo de terreno no está disponible: {%0}
claim.success=Has reclamado el terreno con éxito
claim.form=Reclamar
claim.formxcoord=Coordenada X del terreno
claim.formzcoord=Coordenada Z del terreno
claim.formworld=Nombre del mundo

; Subcomando /p auto
auto.name=auto
auto.alias=a
auto.desc=Te teletransporta al siguiente terreno libre
auto.usage=/p auto [claim: bool] [name: string]
auto.notplotworld=No estás en un mundo de terrenos
auto.success="Teletransportado al terreno libre ({%0};{%1})"
auto.noplots=No se pudo encontrar ningún terreno disponible

; Subcomando /p dispose
dispose.name=dispose
dispose.desc=Elimina tu terreno
dispose.usage=/p dispose
dispose.merged=El terreno no se puede separar. Usa "/p unmerge" o "/p reset confirm".
dispose.confirm=¿Estás seguro de que quieres eliminar el terreno {%0}? Si es así, usa /p dispose confirm
dispose.nomoney=No tienes suficiente dinero para eliminar este terreno
dispose.success=Terreno eliminado

; Subcomando /p reset
reset.name=reset
reset.desc=Elimina y limpia tu terreno
reset.usage=/p reset
reset.confirm=¿Estás seguro de que quieres resetear el terreno {%0}? Si es así, usa /p reset confirm
reset.nomoney=No tienes suficiente dinero para resetear este terreno
reset.success=Terreno reseteado

; Subcomando /p clear
clear.name=clear
clear.desc=Limpia tu terreno
clear.usage=/p clear
clear.confirm=¿Estás seguro de que quieres limpiar el terreno {%0}? Si es así, usa /p clear confirm
clear.nomoney=No tienes suficiente dinero para limpiar este terreno
clear.success=Terreno limpiado

; Subcomando /p biome
biome.name=biome
biome.desc=Cambia la bioma de tu terreno
biome.usage=/p biome [biome: string]
biome.success=Bioma del terreno cambiado a {%0}
biome.invalid=Esa bioma no existe
biome.possible=Biomas posibles: {%0}
biome.form=Bioma

; Subcomando /p biomes
biomes.name=biomes
biomes.desc=Lista todas las biomas disponibles
biomes.usage=/p biomes
biomes.possible=Biomas posibles: {%0}

; Subcomando /p name
name.name=name
name.desc=Establece o cambia el nombre de tu terreno
name.usage=/p name <name: string>
name.success=Terreno renombrado con éxito
name.form=Renombrar
name.formtitle=Nuevo título del terreno

; Subcomando /p home
home.name=home
home.alias=h
home.desc=Viajar a tu terreno
home.usage=/p home [number: int] [world: string]
home.noplots=No posees terrenos en este mundo
home.notexist=No posees un terreno con id {%0} en este mundo
home.success=Teletransportado al terreno {%0} en el mundo {%1}
home.error=No se pudo viajar al terreno
home.form=Casa
home.noplots.target=El jugador no posee terrenos en este mundo
home.notexist.target=El jugador no posee un terreno con id {%0} en este mundo

; Subcomando /p homes
homes.name=homes
homes.desc=Muestra tus terrenos reclamados
homes.usage=/p homes [world: string]
homes.noplots=No posees ningún terreno
homes.header=Terrenos que posees:
homes.form=Casas

; Subcomando /p info
info.name=info
info.alias=i
info.desc=Muestra información sobre un terreno
info.usage=/p info [player: target] [number: int]
info.about=Información del terreno {%0}
info.plotname=Nombre: {%0}
info.owner=Dueño: {%0}
info.helpers=Ayudantes: {%0}
info.denied=Denegados: {%0}
info.biome=Bioma: {%0}
info.flags=Flags: {%0}
info.notfound=No se pudo encontrar ese terreno
info.title=§l§aInformación del Terreno
info.content=§6Información del terreno:§c {%0}\n §r§6Dueño:§c {%1}\n §r§6Descripción:§c {%2}\n §r§6Nombre:§c {%3}\n §r§6Ayudantes:§c {%4}\n §r§6Denegados:§c {%5}\n §r§6Flags:§c {%6}

; UI de renta
rent.info.title=§l§aRenta de Terreno
rent.info.content=§6Información de renta para el terreno:§c {%0}\n §r§6Estado:§c {%1}\n §r§6Monto:§c ${%2}\n §r§6Vence:§c {%3}
rent.pay=Pagar renta
rent.info.button=Alquilar / Pagar
rent.confirm.title=§l§aConfirmar Pago de Renta
rent.confirm.content=§6¿Deseas pagar ${%1} por el terreno {%0}?\n
rent.confirm.pay=Pagar ahora
rent.nosystem=No hay un proveedor de economía disponible.
rent.nofunds=No tienes suficiente dinero para pagar la renta.
rent.paid=Renta pagada: ${%0}
form.close=Cerrar
form.cancel=Cancelar

; Subcomando /p generate
generate.name=generate
generate.alias=gen
generate.desc=Genera un nuevo mundo de terrenos
generate.usage=/p generate <name: string> [teleport: bool] [generatorName: string]
generate.exists=Ya existe un mundo con el nombre {%0}
generate.gexists=El generador {%0} no existe
generate.success=Mundo de terrenos {%0} generado con éxito
generate.error=No se pudo generar el mundo
generate.form=Generación
generate.formworld=Nombre del mundo
generate.formgenerator=Generador del mundo
generate.formteleport=Teletransportarse después de generar

; Subcomando /p give
give.name=give
give.desc=Da tu terreno a otra persona
give.usage=/p give [player: target]
give.notonline=Ese jugador no está en línea
give.maxedout=Ese jugador ha alcanzado el límite de terrenos
give.toself=No puedes dar el terreno a ti mismo
give.confirm=¿Estás seguro de que quieres dar el terreno {%0} al jugador {%1}? Si es así, usa /p give {%1} confirm
give.success=Has dado el terreno a {%0}
give.received={%0} te dio su terreno, {%1}
give.form=Dar
give.dropdown=Destinatario

; Subcomando /p warp
warp.name=warp
warp.desc=Teleportarse a un terreno
warp.usage=/p warp <id: string> [world: string]
warp.wrongid="El id del terreno debe tener el formato X;Z"
warp.notinplotworld=No estás en un mundo de terrenos
warp.unclaimed=No puedes teletransportarte a un terreno sin reclamar
warp.success=Has sido teletransportado al terreno {%0}
warp.form=Warp
warp.formxcoord=Coordenada X del terreno
warp.formzcoord=Coordenada Z del terreno
warp.formworld=Nombre del mundo

; Subcomando /p middle
middle.name=middle
middle.alias=mid
middle.desc=Teletransporta al jugador al centro exacto del terreno al nivel del suelo
middle.usage=/p mid
middle.success=Teletransporte completado

; Subcomando /p setowner
setowner.name=setowner
setowner.desc=Establece el nuevo propietario del terreno sin cobrar nada
setowner.usage=/p setowner <player: target>
setowner.maxplots=Ese jugador alcanzó su límite de terrenos de {%0}
setowner.success={%0} ahora es el propietario de este terreno
setowner.form=Establecer Propietario
setowner.dropdown=Nombre del jugador

; Subcomando /p list
list.name=list
list.alias=l
list.desc=Muestra todos los terrenos de un jugador
list.usage=/p list [player: target]
list.found="Terreno {%0} en ({%1};{%2}),"

; Subcomando /p pvp
pvp.name=pvp
pvp.desc=Activa/desactiva el modo pvp para el terreno
pvp.usage=/p pvp
pvp.world=El PVP está deshabilitado por configuración en este mundo
pvp.plot=El PVP está deshabilitado en este terreno
pvp.disabled=El PVP está deshabilitado aquí
pvp.success=El PVP ahora es {%0} para el terreno

; Subcomando /p clone
clone.name=clone
clone.desc=Clona un terreno a otra ubicación
clone.usage=/p clone <id: string> [world: string]
clone.wrongid="El id del terreno debe tener el formato X;Z"
clone.nomoney=No tienes suficiente dinero para clonar este terreno
clone.success=El terreno {%0} se ha clonado con éxito al terreno {%1}
clone.form=Clonar
clone.formlabel1=Ubicación del terreno original
clone.formlabel2=Ubicación del terreno clonado
clone.formxcoord=Coordenada X del terreno
clone.formzcoord=Coordenada Z del terreno
clone.formworld=Nombre del mundo

; Subcomando /p kick
kick.name=kick
kick.desc=Expulsa a un jugador de tu terreno
kick.usage=/p kick <player: target>
kick.noPlayer=No se encontró al jugador indicado
kick.notInPlot=El jugador indicado no está en tu terreno
kick.cannotkick=No puedes expulsar a este jugador
kick.attemptkick=El jugador {%0} intentó expulsarte
kick.success1=Has expulsado a {%0} del terreno {%1}
kick.success2=El jugador {%0} te expulsó del terreno {%1}
kick.form=Expulsar
kick.dropdown=Nombre del jugador

; Subcomando /p sell
sell.name=sell
sell.desc=Vende un terreno
sell.usage=/p sell <price: float>
sell.unlisted=Tu terreno {%0} ya no está en venta
sell.success=Tu terreno {%0} ahora está en venta por ${%1}

; Subcomando /p buy
buy.name=buy
buy.desc=Compra un terreno
buy.usage=/p buy
buy.noself="No puedes comprar un terreno de ti mismo"
buy.notforsale=Este terreno no está a la venta
buy.confirm=¿Estás seguro de que quieres comprar el terreno {%0} por ${%1}? Para confirmar, usa /p buy confirm
buy.success=Has comprado el terreno {%0} por ${%1}
buy.sold={%0} compró tu terreno ({%1}) por ${%2}

; Subcomando /p border
border.name=border
border.desc=Cambia el borde del terreno
border.alias=b
border.usage=/p border
border.empty=No hay bordes disponibles
border.success=Has cambiado el borde del terreno {%0}
border.merged=¡El terreno no puede estar conectado!
border.title=§l§aFormulario de Bordes
border.content=§6Elige un borde

; Subcomando /p wall
wall.name=wall
wall.desc=Cambia la pared del terreno
wall.alias=w
wall.usage=/p wall
wall.empty=No hay paredes disponibles
wall.success=Has cambiado la pared del terreno {%0}
wall.title=§l§aFormulario de Paredes
wall.content=§6Elige una pared

; Subcomando /p description
description.name=description
description.desc=Cambia la descripción de tu terreno
description.usage=/p description <name: string>
description.success=Descripción del terreno cambiada con éxito
description.formtitle=§6Cambia la descripción del terreno
description.form=§l§aDescripción

; Subcomando /p chat
chat.name=chat
chat.desc=Enviar un mensaje
chat.usage=/p chat <message: string>
chat.define.message=§cPor favor define un mensaje
chat.form=§l§aEnviar un mensaje
chat.formtitle=§6Escribe el mensaje que deseas enviar
chat.format=§l§aPlotChat§r | {%0} §r> {%1}
chat.toggle_on=Chat de terreno activado
chat.toggle_off=Chat de terreno desactivado

; Subcomando /p spawn
spawn.name=spawn
spawn.desc=Establece el punto de aparición de un terreno
spawn.usage=/p spawn
spawn.success=Punto de aparición del terreno cambiado con éxito
spawn.reset=El punto de aparición ha sido restablecido.

; Subcomando /p merge
merge.name=merge
merge.desc=Conecta dos terrenos.
merge.usage=/p merge
merge.wrongFacing=§c¡Mira en la dirección de un terreno!
merge.alreadyMerged=§c¡Los terrenos ya están conectados!
merge.success=§6Tus§c terrenos §6han sido conectados.

; Subcomando /p unmerge
unmerge.name=unmerge
unmerge.desc=Separa tus terrenos.
unmerge.usage=/p unmerge
unmerge.notMerged=§c¡Los terrenos no están conectados!
unmerge.success=§6Tus§c terrenos §6 han sido separados.

; Subcomando /p flags
flags.name=flags
flags.desc=Gestiona los flags del terreno
flags.usage=/p flags <flag_name: string> [value: string|info|remove]
flags.usage.boolean=/p flags {%0} [info|remove]
flags.usage.string=/p flags {%0} [value: string|remove]
flags.usage.position=/p flags {%0} [info|remove]
flags.success=§c{%0} §r§cflag §6ha sido cambiado con éxito.
flags.removed=§c{%0} §r§cflag §6ha sido eliminado con éxito.
flags.info.true=§c{%0} §r§cflag §6está activado.
flags.info.false=§c{%0} §r§cflag §6está desactivado.
flags.info.value=§c{%0} §r§cflag §6contiene el valor§c {%1}§r§6.
flags.info.position=§c{%0} §r§cflag §6contiene la posición§c {%1}, {%2}, {%3}§r§6.
flags.info.not_added=§c{%0} §r§cflag §6no está agregado a la configuración del terreno.
flags.not_exists=§c¡El flag con nombre {%0}§r§c no existe!
